# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
- name: enzopreprocessor.EnzoPreprocessor

# language model
- name: WhitespaceTokenizer
- name: LanguageModelFeaturizer
  model_weights: distilbert-base-uncased
  model_name: distilbert

# Regex for phone numbers
- name: RegexFeaturizer

# dual intentity and entity
- name: DIETClassifier
  random_seed: 42
  batch_size: 32
  intent_classification: True
  entity_recognition: True
  use_masked_language_model: False
  constrain_similarities: True
  epochs: 35
  evaluate_on_number_of_examples: 200
  evaluate_every_number_of_epochs: 1
  tensorboard_log_directory: "./tbdiet"
  tensorboard_log_level: "epoch"

# pretrained spacy NER for PERSON
- name: SpacyNLP
  model: en_core_web_md
- name: SpacyEntityExtractor
  dimensions: [PERSON]

- name: DucklingEntityExtractor
  url: "http://localhost:8000"
  locale: "en_GB"
  timezone: "UTC"
  dimensions: [distance, duration, number, ordinal, phone-number, time, temperature]
  
# other components
- name: FallbackClassifier
  threshold: 0.4
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  constrain_similarities: True

policies:
# No configuration for policies was provided. The following default policies were used to train your model.
# If you'd like to customize them, uncomment and adjust the policies.
# See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
    max_history: 5

  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: action_default_fallback
    enable_fallback_prediction: True
    restrict_rules: True
    check_for_contradictions: True

  # - name: UnexpecTEDIntentPolicy
  #   max_history: 5
  #   epochs: 100

  - name: TEDPolicy
    max_history: 5
    augmentation: 10
    epochs: 100
    constrain_similarities: True
    evaluate_on_number_of_examples: 200
    evaluate_every_number_of_epochs: 1
    tensorboard_log_directory: "./tbted"
    tensorboard_log_level: "epoch"
